### ISSUE TITLE
DaggerAppComponent is not defined?

### ISSUE THREAD

**Issue by renierdbruyn** [Egorand/android-espresso-dagger-testing#1]
am I missing something or does `DaggerAppComponent`  not exist?

https://github.com/Egorand/android-espresso-dagger-testing/blob/9c47e6fd55d79f0c085e2d83e5f9a74a97c54ce5/app/src/main/java/me/egorand/weather/WeatherApp.java#L23

**Comment by Egorand** [comment]
Dagger's annotation processor should generate that class during compilation
